version: '3'
services:
  resume_workshop:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: resume_workshop
    ports:
      - "5000:5000"
    volumes:
      - ..:/app
volumes:
  ..: